#
# nort release configuration 
#
qualification:

  os.command.to.get.installed.version: nort version

build:

publish:
  local.artifact.repository.root: ${M2}
  release.tag: release-something-${current.version}

install:
  installation.directory: ${RUNTIME_DIR}

