#
# nort release configuration 
#
qualification:

  os.command.to.get.installed.version: nort version

build:
  local.artifact.repository.root: ${M2}

publish:

install:
  installation.directory: ${RUNTIME_DIR}

