#
# nort release configuration 
#
qualification:

  os.command.to.get.installed.version: nort version

build:

publish:
  local.artifact.repository.root: ${M2}
  release.tag: nort-release-${current.version}
  truststore:
    file: /Users/ovidiu/.m2/maven.apps.openshift.novaordis.io.truststore
    password: ${NEXUS_TRUSTORE_PASSWORD}

install:
  installation.directory: ${RUNTIME_DIR}

