#!/bin/bash

#
# A wrapper around mvn test
#
# Usage:
#
# t [-c] [-d] [test-class-name]
#

function main() {

    local debug
    local clean
    local class_name
    while [ -n "$1" ]; do
        if [ "$1" = "-c" ]; then
            clean="clean"
        elif [ "$1" = "-d" ]; then
            debug="-Dmaven.surefire.debug=\"-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005\""
        elif [ "${class_name}" = "" ]; then
            class_name=$1
        fi    
        shift
    done

    [ -n "${class_name}" ] && one_test="-Dtest=${class_name}"

    echo mvn ${debug} ${clean} test ${one_test}
    mvn ${debug} ${clean} test ${one_test}
}

main $@